language: csharp

dist: trusty
dotnet: 2.0.0
mono:
  - 5.2.0
  - latest # => "stable release"
  - weekly # => "latest commits"

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - sudo apt-get update -q
  - sudo apt-get install fsharp

install:
  - rvm install 2.2.3
  - gem install bundler

notifications:
  email: false

script:
  - bundle && bundle exec rake

matrix:
  allow_failures:
   - mono: latest
   - mono: weekly