language: csharp

dist: trusty
dotnet: 2.0.0
mono:
  - 5.2.0
  - latest # => "stable release"
  - weekly # => "latest commits"

install:
  - rvm install 2.2.3
  - gem install bundler

notifications:
  email: false

script:
  - FrameworkPathOverride=$MONO_BASE_PATH/4.5-api/ bundle && bundle exec rake

matrix:
  allow_failures:
   - mono: latest
   - mono: weekly