language: csharp

mono:
  - 4.2.3
  - 4.4.1
  - 4.6.0
  - latest # => "stable release"
  - weekly # => "latest commits"

install:
 - rvm install 2.2.3
 - gem install bundler

notifications:
  email: false

script:
 - bundle && bundle exec rake

matrix:
  allow_failures:
   - mono: latest
   - mono: weekly
   - mono: 4.4.1
